version: 2
updates:
- package-ecosystem: npm
  directory: "/app"
  schedule:
    interval: monthly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: ssri
    versions:
    - 6.0.2
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.21.2
    - 5.24.2
    - 5.25.1
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.0
    - 11.0.1
  - dependency-name: "@mdi/font"
    versions:
    - 5.9.55
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
  - dependency-name: bulma
    versions:
    - 0.9.2
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: github.com/spf13/cobra
    versions:
    - 1.1.3
