version: 2
updates:
- package-ecosystem: npm
  directory: "/app"
  schedule:
    interval: monthly
  open-pull-requests-limit: 99
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 99
